### ISSUE TITLE
Linking errors after following all the steps

### ISSUE THREAD

**Issue by sniper0110** [Neargye/hello_tf_win_c_api#1]
Hello,

I followed all of the steps that you mentioned in the readMe file, but I am still facing linking errors.
I tried the hello_tf_win_c_api example and I get the follwoing error in visual studio 2017 : <cannot open source file "c_api.h"> and also  : <identifier "TF_Version" is undefined>.

I followed all the steps including adding the path to tensorflow.dll to the PATH environment variable.

I am on windows 10, visual studio 2017.	

Problem solved! It was just a dumb mistake, I needed to use x64 and Release mode. Thanks for the tutorials!

**Comment by Neargye** [comment]
Hi,

I have added in readme that tensorflow.dll in the repository is compiled in x64 mode. By default TensorFlow build is x64.

If you have any questions or problems, please let me know.

**Comment by sniper0110** [comment]
Thanks for your answer!

In fact I'm trying to make some inference using this API, have you tried anything similar? If yes, then can you share some resources on how to do that? The documentation for the C API is basically non existent!

**Comment by Neargye** [comment]
I've share a couple of examples of how I use interface like [session_run](https://github.com/Neargye/hello_tf_win_c_api/blob/master/src/session_run.cpp) and [interface](https://github.com/Neargye/hello_tf_win_c_api/blob/master/src/interface.cpp).

You can also see tests tensor flow https://github.com/tensorflow/tensorflow/tree/master/tensorflow/c
